language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update
  - composer --version

install:
  - composer install

before_script:
  - mkdir -p build/logs/

script: phpunit --coverage-clover build/logs/clover.xml tests

after_success:
  - php vendor/bin/coveralls
